name: atv18
description: "Altivar 18 Variable Speed Drive Simulator App"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
  fonts:
    - family: PressStart2P
      fonts:
        - asset: fonts/PressStart2P-Regular.ttf
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Regular.ttf

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icon.png"
  adaptive_icon_background: "#ffffff"

